#!/bin/bash
# ld64 编译项目一键设置脚本

echo "=== ld64 编译项目设置 ==="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "【第一步：创建 GitHub 仓库】"
echo "1. 访问 https://github.com/new"
echo "2. 仓库名输入：ld64-build"
echo "3. 选择 Public（公开）"
echo "4. 点击 Create repository"
echo ""
echo "【第二步：上传文件】"
echo "将以下文件上传到仓库："
echo "- .github/workflows/build.yml"
echo "- README.md"
echo ""
echo "【第三步：触发编译】"
echo "1. 进入仓库页面"
echo "2. 点击 Actions 标签"
echo "3. 点击 Build ld64"
echo "4. 点击 Run workflow"
echo "5. 点击绿色的 Run workflow 按钮"
echo ""
echo "【第四步：下载结果】"
echo "1. 等待编译完成（约 5-10 分钟）"
echo "2. 点击编译任务"
echo "3. 滚动到底部 Artifacts 部分"
echo "4. 点击 ld64-linux-x86_64 下载"
echo ""
echo "【第五步：上传到 iSH】"
echo "将下载的 ld64 文件上传到 iSH"
echo ""
echo "=== 设置完成 ==="
